version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.15

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm run test:prod

      - run:
          name: Uplodad code coverage
          command: npm run codecov

      - persist_to_workspace:
          root: ~/repo
          paths: .

  docs-build-deploy:
    <<: *defaults
    steps:
      - checkout

      # Need to find better way to build and deploy the docs.

      - run:
          name: Install docs dependencies
          command: cd docs && npm install

      - run:
          name: Configure dependencies
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

      - run:
          name: Deploy docs to gh-pages branch
          command: cd docs && npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
  docs:
    jobs:
      - docs-build-deploy:
          filters:
            branches:
              only: master
